services:
  db:
    image: postgres:16
    container_name: propslaptops-db
    environment:
      POSTGRES_USER: propslaptops
      POSTGRES_PASSWORD: propslaptops
      POSTGRES_DB: propslaptops_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: propslaptops
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: propslaptops_db
      DB_USER: propslaptops
      DB_PASSWORD: propslaptops
    depends_on:
      - db

volumes:
  postgres_data:
