services:
  app:
    image: cr.yandex/${CR_REGISTRY}/propslaptops:${IMAGE_TAG}
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_ENV=production
    ports:
      - "80:3000"
    restart: always 