services:
  app:
    image: cr.yandex/${{ secrets.YC_CONTAINER_REGISTRY }}/propslaptops:${{ github.event.release.tag_name }}
    environment:
      - DB_HOST=${{ secrets.DB_HOST }}
      - DB_PORT=${{ secrets.DB_PORT }}
      - DB_NAME=${{ secrets.DB_NAME }}
      - DB_USER=${{ secrets.DB_USER }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - NODE_ENV=production
    ports:
      - "80:3000"
    restart: always 