#cloud-config
runcmd:
- [ sudo, chmod, 666, /dev/ttyS1]
users:
- name: {{ env.YC_VM_USER }}
  groups: sudo
  shell: /bin/bash
  sudo: 'ALL=(ALL) NOPASSWD:ALL'
  ssh_authorized_keys:
  - {{ env.YC_VM_USER_SSH_KEY }}
