name: Deploy to Yandex Cloud Serverless Containers

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  CR_REGISTRY: ${{ secrets.YC_CONTAINER_REGISTRY }}
  FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
  DEPLOY_SA_ID: ${{ secrets.YC_DEPLOY_SA_ID }}
  RUNTIME_SA_ID: ${{ secrets.YC_RUNTIME_SA_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Yandex Cloud IAM token
        id: get-iam-token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Login to Yandex Container Registry
        uses: docker/login-action@v3
        with:
          registry: cr.yandex
          username: iam
          password: ${{ steps.get-iam-token.outputs.token }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.event.release.tag_name }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/propslaptops:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/propslaptops:$IMAGE_TAG

      - name: Deploy to Serverless Container
        uses: yc-actions/yc-sls-container-deploy@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          container-name: propslaptops
          folder-id: ${{ env.FOLDER_ID }}
          revision-service-account-id: ${{ env.RUNTIME_SA_ID }}
          revision-cores: 1
          revision-memory: 512Mb
          revision-core-fraction: 100
          revision-concurrency: 8
          revision-image-url: cr.yandex/${{ env.CR_REGISTRY }}/propslaptops:${{ github.event.release.tag_name }}
          revision-execution-timeout: 30
          public: true
          revision-network-id: ${{ secrets.YC_NETWORK_ID }}
          revision-env: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            NODE_ENV=production 